package com.autodoc.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    DUPLICATE_EMAIL,
    TEAM_NOT_FOUND,
    INVALID_CREDENTIALS,
    INACTIVE_USER,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INVALID_REQUEST,
    DUPLICATE_TEAM_NAME,
    TEMPLATE_NOT_FOUND,
    DOCUMENT_NOT_FOUND,
    INVALID_DOCUMENT_FORMAT,
    SHEET_COLUMN_NOT_FOUND,
    SHEET_ROW_NOT_FOUND
}
