package com.autodoc.common.exception;

public enum ErrorCode {
    USER_NOT_FOUND,
    DUPLICATE_EMAIL,
    TEAM_NOT_FOUND,
    INVALID_CREDENTIALS,
    INACTIVE_USER,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INVALID_REQUEST,
    DUPLICATE_TEAM_NAME,
    TEMPLATE_NOT_FOUND
}
